version: '3.8'

services:
  backend:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8000:8000"
    volumes:
      - ./service:/app
    networks:
      - app-network
    environment:
      - ENV_VAR_NAME=env_var_value  # Add your environment variables here
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 2

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - ENV_VAR_NAME=env_var_value  # Add your environment variables here
    depends_on:
      backend:
        condition: service_healthy
    command: /bin/sh -c "sleep 10 && npm run dev"

networks:
  app-network:
    driver: bridge
